# global words

# with open("words.json") as f:
#     words = json.load(f)


food_words = [
    {"das Essen": "food"},
    {"die Mahlzeit": "meal"},
    {"das Frühstück": "breakfast"},
    {"das Mittagessen": "lunch"},
    {"das Abendessen": "dinner"},
    {"der Snack": "snack"},
    {"der Apfel": "apple"},
    {"die Banane": "banana"},
    {"die Orange": "orange"},
    {"die Erdbeere": "strawberry"},
    {"die Traube": "grape"},
    {"die Wassermelone": "watermelon"},
    {"das Gemüse": "vegetables"},
    {"die Karotte": "carrot"},
    {"die Tomate": "tomato"},
    {"die Kartoffel": "potato"},
    {"der Salat": "salad"},
    {"der Spinat": "spinach"},
    {"die Zwiebel": "onion"},
    {"der Knoblauch": "garlic"},
    {"das Fleisch": "meat"},
    {"das Huhn": "chicken"},
    {"der Fisch": "fish"},
    {"das Rindfleisch": "beef"},
    {"der Schweinebraten": "pork roast"},
    {"der Käse": "cheese"},
    {"die Milch": "milk"},
    {"der Joghurt": "yogurt"},
    {"die Butter": "butter"},
    {"das Brot": "bread"},
    {"die Nudeln": "pasta"},
    {"der Reis": "rice"},
    {"die Suppe": "soup"},
    {"der Kaffee": "coffee"},
    {"der Tee": "tea"},
    {"die Limonade": "lemonade"},
    {"das Wasser": "water"},
    {"der Wein": "wine"},
    {"das Bier": "beer"},
    {"der Kuchen": "cake"},
    {"der Keks": "cookie"},
    {"die Schokolade": "chocolate"},
    {"das Eis": "ice cream"},
    {"der Honig": "honey"},
    {"der Senf": "mustard"},
    {"die Mayonnaise": "mayonnaise"},
    {"das Öl": "oil"},
    {"der Essig": "vinegar"},
]


general_words = [
    {"der Abend": "evening"},
    {"der Wochenende": "weekend"},
    {"der Monat": "month"},
    {"das Jahr": "year"},
    {"der Geburtstag": "birthday"},
    {"die Kinder": "children"},
    {"die Eltern": "parents"},
    {"die Liebe": "love"},
    {"der Hass": "hate"},
    {"das Glück": "luck"},
    {"die Traurigkeit": "sadness"},
    {"die Freude": "joy"},
    {"der Schmerz": "pain"},
    {"die Gesundheit": "health"},
    {"die Krankheit": "illness"},
    {"der Arzt": "doctor"},
    {"das Krankenhaus": "hospital"},
    {"die Apotheke": "pharmacy"},
    {"das Telefon": "telephone"},
    {"der Computer": "computer"},
    {"das Internet": "internet"},
    {"die Musik": "music"},
    {"der Film": "movie"},
    {"das Buch": "book"},
    {"die Kunst": "art"},
    {"der Sport": "sport"},
    {"der Fußball": "football/soccer"},
    {"der Basketball": "basketball"},
    {"das Schwimmen": "swimming"},
    {"das Fahrrad": "bicycle"},
]

city_words = [
    [
        {"die Stadt": "city"},
        {"das Zentrum": "center"},
        {"der Bahnhof": "train station"},
        {"die U-Bahn": "subway"},
        {"die Bushaltestelle": "bus stop"},
        {"die Straße": "street"},
        {"die Kreuzung": "intersection"},
        {"der Platz": "square"},
        {"das Gebäude": "building"},
        {"der Wolkenkratzer": "skyscraper"},
        {"das Einkaufszentrum": "shopping mall"},
        {"das Kino": "cinema"},
        {"das Theater": "theater"},
        {"das Museum": "museum"},
        {"die Bibliothek": "library"},
        {"der Park": "park"},
        {"der Spielplatz": "playground"},
        {"das Café": "café"},
        {"das Restaurant": "restaurant"},
        {"die Bar": "bar"},
        {"die Diskothek": "nightclub"},
        {"der Supermarkt": "supermarket"},
        {"die Bank": "bank"},
        {"das Büro": "office"},
        {"das Rathaus": "town hall"},
        {"die Apotheke": "pharmacy"},
        {"das Krankenhaus": "hospital"},
        {"die Schule": "school"},
        {"die Universität": "university"},
        {"das Hotel": "hotel"},
        {"der Markt": "market"},
        {"der Laden": "shop/store"},
        {"das Kaufhaus": "department store"},
        {"die Post": "post office"},
        {"die Kirche": "church"},
        {"die Synagoge": "synagogue"},
        {"die Moschee": "mosque"},
        {"der Tempel": "temple"},
        {"die Brücke": "bridge"},
        {"der Fluss": "river"},
        {"der See": "lake"},
        {"der Parkplatz": "parking lot"},
        {"die Ampel": "traffic light"},
        {"der Zebrastreifen": "crosswalk"},
        {"der Fahrradweg": "bike lane"},
        {"die Treppe": "stairs"},
        {"der Aufzug": "elevator"},
        {"die Straßenbahn": "tram"},
        {"das Denkmal": "monument"},
        {"der Turm": "tower"},
    ]
]

weather_words = [
    [
        {"das Wetter": "weather"},
        {"die Sonne": "sun"},
        {"der Mond": "moon"},
        {"die Sterne": "stars"},
        {"der Himmel": "sky"},
        {"die Wolke": "cloud"},
        {"der Regen": "rain"},
        {"der Schnee": "snow"},
        {"der Hagel": "hail"},
        {"der Sturm": "storm"},
        {"der Wind": "wind"},
        {"der Nebel": "fog"},
        {"der Blitz": "lightning"},
        {"der Donner": "thunder"},
        {"die Temperatur": "temperature"},
        {"der Grad": "degree"},
        {"der Frost": "frost"},
        {"der Schauer": "shower"},
        {"der Niederschlag": "precipitation"},
        {"die Feuchtigkeit": "humidity"},
        {"der Sonnenschein": "sunshine"},
        {"die Hitze": "heat"},
        {"die Kälte": "cold"},
        {"der Frühling": "spring"},
        {"der Sommer": "summer"},
        {"der Herbst": "autumn/fall"},
        {"der Winter": "winter"},
        {"die Jahreszeit": "season"},
        {"der Sonnenaufgang": "sunrise"},
        {"der Sonnenuntergang": "sunset"},
        {"der Regenbogen": "rainbow"},
        {"der Schirm": "umbrella"},
        {"die Jacke": "jacket"},
        {"der Mantel": "coat"},
        {"die Mütze": "hat"},
        {"der Schal": "scarf"},
        {"die Handschuhe": "gloves"},
        {"die Sonnenbrille": "sunglasses"},
        {"der Strand": "beach"},
        {"die Welle": "wave"},
        {"das Gewitter": "thunderstorm"},
        {"das Klima": "climate"},
        {"die Vorhersage": "forecast"},
        {"die Wetterkarte": "weather map"},
        {"der Wetterbericht": "weather report"},
        {"der Hitzewelle": "heatwave"},
        {"die Kaltfront": "cold front"},
        {"der Tornado": "tornado"},
        {"das Erdbeben": "earthquake"},
    ]
]

driver_license_words = [
    [
        {"abendlicht": "low beams"},
        {"fernlicht": "high beams"},
        {"blinklicht": "turn signal"},
        {"bremslicht": "brake light"},
        {"rücklicht": "reverse light"},
        {"rückstrahler": "reflector"},
        {"bremslicht": "brake light"},
        {"motor kühlmittelkontrolle": "engine coolant check"},
        {"motor kühlwasser": "engine coolant"},
        {"scneiben wasser": "windshield washer"},
        {"keine beschädigung": "no damage"},
        {"reifen lüftdruck": "tire pressure"},
        {"reifen profil": "tire profile"},
        {"motor öl kontrolle": "engine oil check"},
        {"kennzeichenlicht": "license plate light"},
        {"nebelschlussleuchte": "fog light"},
        {"warnblinklicht": "hazard light"},
        {"hupe": "horn"},
        {"standlicht": "parking light"},
        {"gefahrbremsung": "emergency stop"},
    ]
]

words = food_words + general_words + city_words + weather_words
